//
// Created by jefflee on 2023/8/8.
//

#ifndef PLAYERSDK_MEDIA_CACHE_SRC_MAIN_CPP_PROXY_CACHE_MANAGER_H_
#define PLAYERSDK_MEDIA_CACHE_SRC_MAIN_CPP_PROXY_CACHE_MANAGER_H_

class proxy_cache_manager {

};

#endif //PLAYERSDK_MEDIA_CACHE_SRC_MAIN_CPP_PROXY_CACHE_MANAGER_H_
